RTC-14942 Fix toast notifiaction vertical position
finos/SymphonyElectron pull request #2113
Opened 2024-03-14 16:28 UTC by baphony

https://perzoinc.atlassian.net/browse/RTC-14942

Notification position is fine but Toast notifications were vertically inverted on Windows:
![image](https://github.com/finos/SymphonyElectron/assets/112877883/9950a3c1-811b-43dc-a9ff-ec4d94841d86)

2024-03-14 16:32 UTC, swasunb approved these changes

2024-03-15 00:11 UTC, axeleriksson147 approved these changes

2024-03-15 02:31 UTC, KiranNiranjan requested changes
@baphony This is not a bug we intentionally positioned the **call** toast notification position exactly opposite to the **message** toast notification

2024-03-15 07:42 UTC, baphony commented
Thanks for the information, would it be good to have some information about it in the notification settings, close by the "Set position" button, to avoid confusion?

I close this PR

2024-03-15 07:42 UTC, closed without merging